server:
  port: 8087
  servlet:
    context-path: /api

    # session???? ????
    session:
      timeout: 1800
spring:
  # ????
  application:
    name: back

  # ?? dev ??
  profiles:
     active: dev

  # ?????
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///bishe?characterEncoding=utf-8
    username: root
    password: chen1213
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    # lombok ????
    static-path-pattern: /static/**

  # ????
  servlet:
    multipart:
      # ????
      max-file-size: 10MB

mybatis-plus:
  global-config:
    db-config:

      #???????
#      column-underline: true

      #??????
      logic-delete-value: 0  # ????? ???0
      logic-not-delete-value: 1  # ??????? ???1
      db-type: mysql # ?????

      # ??????????????
      # ???? false ???????????????????????MyBatis-Plus ?????????
      # ?????????????????????????????????????????????????????
    refresh: false
  configuration:
    # ?????????????????????????????(java?????????????????????)
    # ???? `true` ???????????????????? `user_name`??
    # ???? Java ?????????????????? `userName`??????????????????????
#    map-underscore-to-camel-case: true

    # ???????? MyBatis ??????????
    # ???? `false` ????? MyBatis ????????
    # ?????????????????????????????????????????
    cache-enabled: false

    # ??????? MyBatis ??????????
    # ???????????????????????????????????????????????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # ??????? MyBatis Mapper XML ??????
  # ??? XML Mapper ??????????????? SQL ???????
  #mapper-locations: classpath:/mapper/*.xml

