server:
  port: 8088

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///aaa?characterEncoding=utf-8
    username: root
    password: chen1213
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**

mybatis-plus:
  global-config:
    db-config:

      #???????
      column-underline: true

      #??????
      logic-delete-value: 0  # ????? ???0
      logic-not-delete-value: 1  # ??????? ???1
      db-type: mysql # ?????

    # ??????????????
    # ???? false ???????????????????????MyBatis-Plus ?????????
    # ?????????????????????????????????????????????????????
    refresh: false
  configuration:
    # ?????????????????????????????(java?????????????????????)
    # ???? `true` ???????????????????? `user_name`??
    # ???? Java ?????????????????? `userName`??????????????????????
    map-underscore-to-camel-case: true

    # ???????? MyBatis ??????????
    # ???? `false` ????? MyBatis ????????
    # ?????????????????????????????????????????
    cache-enabled: false

    # ??????? MyBatis ??????????
    # ???????????????????????????????????????????????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # ??????? MyBatis Mapper XML ??????
  # ??? XML Mapper ??????????????? SQL ????????
  #mapper-locations: classpath:/mapper/*.xml

